### ISSUE TITLE
HttpResponseException: Service Unavailable:

### ISSUE THREAD

**Issue by LittlePonyta** [horrorho/InflatableDonkey#16]
Hello there,

When retrieving a certain backup, I stumbled upon this error:

```
Exception in thread "main" org.apache.http.client.HttpResponseException: Service Unavailable: <html><body><b>Http/1.1 Service Unavailable</b></body> </html>
        at com.github.horrorho.inflatabledonkey.responsehandler.DonkeyResponseHandler.handleResponse(DonkeyResponseHandler.java:53)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:222)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:164)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:139)
        at com.github.horrorho.inflatabledonkey.cloud.AuthorizeAssets.authorizeGet(AuthorizeAssets.java:115)
        at com.github.horrorho.inflatabledonkey.cloud.AuthorizeAssets.authorize(AuthorizeAssets.java:97)
        at com.github.horrorho.inflatabledonkey.DownloadAssistant.download(DownloadAssistant.java:81)
        at com.github.horrorho.inflatabledonkey.Backup.download(Backup.java:138)
        at com.github.horrorho.inflatabledonkey.Backup.download(Backup.java:102)
        at com.github.horrorho.inflatabledonkey.Main.main(Main.java:221)
```

I may be wrong, but this is because the tree path is too long and then this error occurs. Because I tried to delete that folder but then it gives an error that it can't delete because Source Path is too long.

Any ideas on fixing this if that's the case? Or is it maybe some other problem? Thanks beforehand

**Comment by horrorho** [comment]
Hi there. Http/1.1 Service Unavailable, the server doesn't want to talk to you about that request. I'd initially just wait and try again in a few hours time. 

I'm not sure how it would be related to a directory path issue. You can try downloading your backup closer to the root folder of the drive. If the iCloud backup has deeply nested directories/ long paths you can hit the file path limit if you also download into a nested directory/ long path.

**Comment by horrorho** [comment]
If it persists, let me know and I'll talk you through configuring logs so we can see what's going on in a bit more detail.

**Comment by LittlePonyta** [comment]
Yeah, probably a network issue, but it is strange because it first download and then always stops at the same file and then give that error. Thanks anyways

**Comment by horrorho** [comment]
File data is stored on third party servers. If a file contains a reference to server that's experiencing issues then, as you describe, it will continue to fail until that server sorts itself out.
