### ISSUE TITLE
Compilation Issue OSX

### ISSUE THREAD

**Issue by topi23** [horrorho/InflatableDonkey#21]
On OSX 10.10

When I run `mvn package` I get this error :
```
src/main/java/com/github/horrorho/inflatabledonkey/SnapshotSelector.java:[67,25] incompatible types: inferred type does not conform to upper bound(s)
    inferred: ? extends java.util.Collection<com.github.horrorho.inflatabledonkey.data.backup.Snapshot>
    upper bound(s): java.util.Collection<com.github.horrorho.inflatabledonkey.data.backup.Snapshot>,java.lang.Object

	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```
Any idea ?

Thanks !

**Comment by horrorho** [comment]
Hi there. Which version of Java are you using?
```
java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
```

**Comment by topi23** [comment]
```
java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
```

**Comment by horrorho** [comment]
Ok Java version 1.8.0_25 is like a couple of years old I think. Are you able to update it to a newer version and try again?

**Comment by topi23** [comment]
Well, I update java, but I have the same error...

```
java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
```

**Comment by horrorho** [comment]
That's odd. Have you tried rebooting your machine? It's just I can compile without issue.

**Comment by horrorho** [comment]
Also if you could please:
```
mvn --version
```
and let me know the Java version.

**Comment by topi23** [comment]
I remove all java components from my computer, and re-install them. And compilation works !

Thank you for your time !

**Comment by horrorho** [comment]
Good work and thank you for letting me know!
