### ISSUE TITLE
MobileMe Terms of Service Update

### ISSUE THREAD

**Issue by Aliasr** [horrorho/InflatableDonkey#25]
Hi @horrorho . I'm getting this error. Any idea?

```
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>protocolVersion</key>
		<string>2</string>

		<key>localizedError</key>
		<string>MOBILEME_TERMS_OF_SERVICE_UPDATE</string>

	</dict>
</plist>
	at com.github.horrorho.inflatabledonkey.responsehandler.DonkeyResponseHandler.handleResponse(DonkeyResponseHandler.java:53)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:222)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:164)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:139)
	at com.github.horrorho.inflatabledonkey.cloud.accounts.Accounts.account(Accounts.java:56)
	at com.github.horrorho.inflatabledonkey.Main.main(Main.java:138)
```

**Comment by horrorho** [comment]
"MOBILEME_TERMS_OF_SERVICE_UPDATE"

Hi. The iCloud account is not in a valid state, the most recent terms of service have not been accepted.

You can visit [iCloud](https://www.icloud.com/) to rectify this, although you're unlikely to have any iOS 9 backups in there.
