### ISSUE TITLE
Failed Decode, retrieved files unreadable.

### ISSUE THREAD

**Issue by mupet0000** [horrorho/InflatableDonkey#3]
Hi,

I understand that this is experimental software, so I'm not sure if this is a known issue or not. I'm trying to recover a backup from my iCloud account but the files are not being decrypted for some reason, I've had some success with another iCloud account as a test, but none with my own, not really sure why as they are both from iPhones running iOS9.

The files are downloaded but are unreadable and this is what is shown in the output:
`11:29:25.289 [main] WARN  c.g.h.i.data.der.DERUtils - -- parse() - failed decode: {}
java.lang.IllegalArgumentException: tag mismatch, expected 1 got 2490
        at com.github.horrorho.inflatabledonkey.data.der.DER.asApplicationSpecific(DER.java:121) ~[InflatableDonkey.jar:na]
        at com.github.horrorho.inflatabledonkey.data.der.ProtectionInfo.<init>(ProtectionInfo.java:109) ~[InflatableDonkey.jar:na]
        at com.github.horrorho.inflatabledonkey.data.der.DERUtils.parse(DERUtils.java:57) [InflatableDonkey.jar:na]
        at com.github.horrorho.inflatabledonkey.data.der.DERUtils.parse(DERUtils.java:47) [InflatableDonkey.jar:na]
        at com.github.horrorho.inflatabledonkey.pcs.xzone.ProtectionZoneAssistant.importProtectionInfo(ProtectionZoneAssistant.java:161) [InflatableDonkey.jar:na]
        at com.github.horrorho.inflatabledonkey.pcs.xzone.ProtectionZone.newProtectionZone(ProtectionZone.java:123) [InflatableDonkey.jar:na]
        at com.github.horrorho.inflatabledonkey.pcs.xzone.ProtectionZone.newProtectionZone(ProtectionZone.java:116) [InflatableDonkey.jar:na]
        at com.github.horrorho.inflatabledonkey.cloud.clients.AssetTokenClient.asset(AssetTokenClient.java:94) [InflatableDonkey.jar:na]
        at com.github.horrorho.inflatabledonkey.cloud.clients.AssetTokenClient.lambda$assets$0(AssetTokenClient.java:87) [InflatableDonkey.jar:na]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[na:1.8.0_91]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[na:1.8.0_91]
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[na:1.8.0_91]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:1.8.0_91]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:1.8.0_91]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:1.8.0_91]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[na:1.8.0_91]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:1.8.0_91]
        at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[na:1.8.0_91]
        at com.github.horrorho.inflatabledonkey.cloud.clients.AssetTokenClient.assets(AssetTokenClient.java:90) [InflatableDonkey.jar:na]
        at com.github.horrorho.inflatabledonkey.Backup.assets(Backup.java:113) ~[InflatableDonkey.jar:na]
        at com.github.horrorho.inflatabledonkey.Main.main(Main.java:241) `~[InflatableDonkey.jar:na]`

Thanks for your hard work!

**Comment by njonjo1985** [comment]
https://github.com/hackappcom/iloot/issues/62#issuecomment-213391984

**Comment by horrorho** [comment]
Sorry for the delay. I've pushed a new build that you may like to test.

**Comment by horrorho** [comment]
Closing the ticket, please re-open if  the issue persists despite the code fixes. Thank you.
