### ISSUE TITLE
Out of memory for large backup 

### ISSUE THREAD

**Issue by vipinbeni** [horrorho/InflatableDonkey#97]
Hi Sir, @horrorho , @Aliasr ,@oct-test ,@dirkwirth @Blokh

please help me ..
i am tried to download a icloud backup of 42 gb in size using your source but i got  below error code is working fine for small backups but for this large backup it **throwing out of memory error** 

 A: DEVICE 7FBEFAB4A1D82BE321B26AA10FA0CFD35F5885B3 iPhone8,2 N66mAP
 0:	  42 GB USER’s iPhone (11.3.1)  2018-12-18T12:10:05.157Z
 1:	  20 MB USER’s iPhone (11.3.1)  2018-12-21T09:11:21.609Z

Enter selection (multiple values accepted, leave blank to select all, q to quit):
: 0
Retrieving snapshot:   42 GB USER’s iPhone (11.3.1)  2018-12-18T12:10:05.157Z

Exception in thread "main" java.lang.RuntimeException: java.lang.OutOfMemoryError
	at com.github.horrorho.inflatabledonkey.cloudkitty.CloudKitty.execute(CloudKitty.java:162)
	at com.github.horrorho.inflatabledonkey.cloudkitty.CloudKitty.get(CloudKitty.java:115)
	at com.github.horrorho.inflatabledonkey.cloudkitty.operations.QueryRetrieveRequestOperations.get(QueryRetrieveRequestOperations.java:62)
	at com.github.horrorho.inflatabledonkey.cloud.clients.AssetTokenClient.apply(AssetTokenClient.java:69)
	at com.github.horrorho.inflatabledonkey.BackupAssistant.assets(BackupAssistant.java:139)
	at com.github.horrorho.inflatabledonkey.Backup.downloadSnapshot(Backup.java:137)
	at com.github.horrorho.inflatabledonkey.Backup.download(Backup.java:104)
	at com.github.horrorho.inflatabledonkey.Main.main(Main.java:376)
Caused by: java.lang.OutOfMemoryError
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.util.concurrent.ForkJoinTask.getThrowableException(Unknown Source)
	at java.util.concurrent.ForkJoinTask.get(Unknown Source)
	at com.github.horrorho.inflatabledonkey.cloudkitty.CloudKitty.execute(CloudKitty.java:136)
	... 7 more
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOfRange(Unknown Source)
	at com.google.protobuf.ByteString$ArraysByteArrayCopier.copyFrom(ByteString.java:121)
	at com.google.protobuf.ByteString.copyFrom(ByteString.java:298)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readBytes(CodedInputStream.java:2328)
	at com.github.horrorho.inflatabledonkey.protobuf.CloudKit$Record$Type.<init>(CloudKit.java:34841)
	at com.github.horrorho.inflatabledonkey.protobuf.CloudKit$Record$Type.<init>(CloudKit.java:34817)
	at com.github.horrorho.inflatabledonkey.protobuf.CloudKit$Record$Type$1.parsePartialFrom(CloudKit.java:34876)
	at com.github.horrorho.inflatabledonkey.protobuf.CloudKit$Record$Type$1.parsePartialFrom(CloudKit.java:1)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2315)
	at com.github.horrorho.inflatabledonkey.protobuf.CloudKit$Record.<init>(CloudKit.java:30387)
	at com.github.horrorho.inflatabledonkey.protobuf.CloudKit$Record.<init>(CloudKit.java:30340)
	at com.github.horrorho.inflatabledonkey.protobuf.CloudKit$Record$1.parsePartialFrom(CloudKit.java:30535)
	at com.github.horrorho.inflatabledonkey.protobuf.CloudKit$Record$1.parsePartialFrom(CloudKit.java:1)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2315)
	at com.github.horrorho.inflatabledonkey.protobuf.CloudKit$QueryRetrieveResponse$QueryResult.<init>(CloudKit.java:18312)
	at com.github.horrorho.inflatabledonkey.protobuf.CloudKit$QueryRetrieveResponse$QueryResult.<init>(CloudKit.java:18254)
	at com.github.horrorho.inflatabledonkey.protobuf.CloudKit$QueryRetrieveResponse$QueryResult$1.parsePartialFrom(CloudKit.java:18350)
	at com.github.horrorho.inflatabledonkey.protobuf.CloudKit$QueryRetrieveResponse$QueryResult$1.parsePartialFrom(CloudKit.java:1)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2315)
	at com.github.horrorho.inflatabledonkey.protobuf.CloudKit$QueryRetrieveResponse.<init>(CloudKit.java:18122)
	at com.github.horrorho.inflatabledonkey.protobuf.CloudKit$QueryRetrieveResponse.<init>(CloudKit.java:18094)
	at com.github.horrorho.inflatabledonkey.protobuf.CloudKit$QueryRetrieveResponse$1.parsePartialFrom(CloudKit.java:18163)
	at com.github.horrorho.inflatabledonkey.protobuf.CloudKit$QueryRetrieveResponse$1.parsePartialFrom(CloudKit.java:1)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2315)
	at com.github.horrorho.inflatabledonkey.protobuf.CloudKit$ResponseOperation.<init>(CloudKit.java:5270)
	at com.github.horrorho.inflatabledonkey.protobuf.CloudKit$ResponseOperation.<init>(CloudKit.java:5185)
	at com.github.horrorho.inflatabledonkey.protobuf.CloudKit$ResponseOperation$1.parsePartialFrom(CloudKit.java:5308)
	at com.github.horrorho.inflatabledonkey.protobuf.CloudKit$ResponseOperation$1.parsePartialFrom(CloudKit.java:1)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:197)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:215)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:220)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)

please help me where we need to correct..

**Comment by vipinbeni** [comment]
it is going out from here 

![1d](https://user-images.githubusercontent.com/5228833/51512462-1caced00-1e2c-11e9-8cc5-147f6e061a0e.jpg)

 List<SimpleImmutableEntry<Integer, List<ResponseOperation>>> get
                    = forkJoinPool.submit(() -> list.parallelStream()
                    .map(u -> new SimpleImmutableEntry<>(u.getKey(), request(httpClient, api, header, u.getValue())))
                    .collect(toList()))
                            .get();

**Comment by vipinbeni** [comment]
this tool working on the same backup anybody please help to find out the problem 

https://www.fonelab.com/ios-data-recovery/

**Comment by vipinbeni** [comment]
Any body please help to short out the same .. @horrorho , @Aliasr ,@oct-test ,@dirkwirth @Blokh

**Comment by Aliasr** [comment]
Hi @vipinbeni. Try increasing the maximum heap size. You can use the -Xmx flag when calling Inflatable Donkey.

`~/InflatableDonkey-master/target $ java -Xmx2g -jar InflatableDonkey.jar username password`

Use -Xmx1g for 1GB, -Xmx2g for 2GB, -Xmx4g for 4GB and so on...

**Comment by vipinbeni** [comment]
Thanks a lot @Aliasr

**Comment by vipinbeni** [comment]
Hi Sir @Aliasr  please tell me whre i am doing wrong ..
to download a backup with 2FA 
i need  to clear my problem with you all that i am adding 6 digit code at end of password  like  if code is 989898 but i **got bad apple id or password error** please tell me where and how we add the 6 digit code in arguments  please help ... 

 "vipin.beniwal722@gmail.com" "mypassword989898"
  I try to login www.icloud.com, as I've enabled 2FA, it request me to input 2FA code after login/pass.
    I see popup on my associated iPhone with 6-digit code
    Then I use InflatableDonkey to get token by adding that 6-digit code to my pass
